lang_ext = {
"ABAP": (".abap", ),
"ActionScript": (".as", ),
"Ada": (".ada", ".adb", ".ads", ".pad", ),
"ADSO/IDSM": (".adso", ),
"AMPLE": (".ample", ".dofile", ".startup", ),
"Ant": (".build.xml", ),
"Apex Trigger": (".trigger", ),
"Arduino Sketch": (".ino", ".pde", ),
"ASP": (".asa", ".asp", ),
"ASP.Net": (".asax", ".ascx", ".asmx", ".aspx", ".config", ".master", ".sitemap", ".webinfo", ),
"Assembly": (".asm", ".s", ".S", ),
"AutoHotkey": (".ahk", ),
"awk": (".awk", ),
"Bash": (".bash", ),
"Shell": (".sh", ),
"C": (".c", ".ec", ".pgc", ),
"C Shell": (".csh", ".tcsh", ),
"C": (".cs", ),
"C": (".C", ".c++," ".cc", ".cpp", ".cxx", ".pcc", ),
"C/C++": (".h", ".H", ".hh", ".hpp", ),
"CCS": (".ccs", ),
"Clojure": (".clj", ),
"CljScript": (".cljs", ),
"CMake": (".cmake", ".CMakeLists.txt", ),
"COBOL": (".cbl", ".CBL", ".cob", ".COB", ),
"CoffeeScript": (".coffee", ),
"ColdFusion": (".cfm", ),
"CFScript": (".cfc", ),
"CSS": (".css", ),
"CUDA": (".cu", ),
"Cython": (".pyx", ),
"D/dtrace": (".d", ),
"DAL": (".da", ),
"Dart": (".dart", ),
"diff": (".diff", ),
"DITA": (".dita", ),
"Batch": (".bat", ".BAT", ".btm", ".BTM", ".cmd", ".CMD", ),
"DTD": (".dtd", ),
"ECPP": (".ecpp", ),
"Elixir": (".ex", ".exs", ),
"ERB": (".ERB", ".erb", ),
"Erlang": (".erl", ".hrl", ),
"Expect": (".exp", ),
"F": (".fs", ".fsi", ),
"Focus": (".focexec", ),
"Fortran77": (".f", ".F", ".f77", ".F77", ".for", ".FOR", ".FTN", ".ftn", ".pfo", ),
"Fortran90": (".f90", ".F90", ),
"Fortran95": (".f95", ".F95", ),
"Go": (".go", ),
"Grails": (".gsp", ),
"Groovy": (".gant", ".gradle", ".groovy", ),
"Haml": (".haml", ),
"Handlebars": (".handlebars", ".hbs", ),
"Harbour": (".hb", ),
"Haskell": (".hs", ".lhs", ),
"HLSL": (".cg", ".cginc", ".shader", ),
"HTML": (".htm", ".html", ),
"IDL": (".idl", ),
"IDL/Qt Project/Prolog": (".pro", ),
"InstallShield": (".ism", ),
"Java": (".java", ),
"Js": (".js", ),
"JavaServerFaces": (".jsf", ".xhtml", ),
"JCL": (".jcl", ),
"JSON": (".json", ),
"JSP": (".jsp", ".jspf", ),
"Kermit": (".ksc", ),
"KornShell": (".ksh", ),
"Kotlin": (".kt", ),
"LESS": (".less", ),
"lex": (".l", ),
"Lisp": (".el", ".lisp", ".lsp", ".sc", ),
"Lisp/Julia": (".jl", ),
"Lisp/OpenCL": (".cl", ),
"OScript": (".oscript", ),
"Lua": (".lua", ),
"m4": (".ac", ".m4", ),
"make": (".am", ".gnumakefile", ".Gnumakefile", ".makefile", ".Makefile", ),
"MATLAB": (".m", ),
"Maven": (".pom", ".pom.xml", ),
"Modula3": (".i3", ".ig", ".m3", ".mg", ),
"MSBuild": (".csproj", ".vbproj", ".vcproj", ".wdproj", ".wixproj", ),
"MUMPS": (".mps", ".m", ),
"Mustache": (".mustache", ),
"MXML": (".mxml", ),
"NAnt": (".build", ),
"DMAP": (".dmap", ),
"ObjectiveC": (".m", ".mm", ),
"Caml": (".ml", ".mli", ".mll", ".mly", ),
"OracleForms": (".fmt", ),
"OracleReports": (".rex", ),
"Pascal": (".dpr", ".p", ".pas", ),
"Pascal/Puppet": (".pp", ),
"Patran": (".pcl", ".ses", ),
"Perl": (".perl", ".plh", ".plx", ".pm", ),
"Perl/Prolog": (".PL", ".pl", ),
"PHP": (".php", ".php3", ".php4", ".php5", ),
"PHP/Pascal": (".inc", ),
"PigLatin": (".pig", ),
"PL/I": (".pl1", ),
"PowerShell": (".ps1", ),
"Prolog": (".P", ),
"ProtocolBuffers": (".proto", ),
"PureScript": (".purs", ),
"Python": (".py", ),
"QML": (".qml", ),
"R": (".R", ),
"Racket": (".rkt", ".rktl", ".sch", ".scm", ".scrbl", ".ss", ),
"Razor": (".cshtml", ),
"Rexx": (".rexx", ),
"RobotFramework": (".robot", ".tsv", ),
"Ruby": (".rake", ".rb", ),
"Ruby HTML": (".rhtml", ),
"Rust": (".rs", ),
"SAS": (".sas", ),
"SASS": (".sass", ".scss", ),
"Scala": (".scala", ),
"sed": (".sed", ),
"SKILL": (".il", ),
"SKILL++": (".ils", ),
"Smarty": (".smarty", ".tpl", ),
"Softbridge Basic": (".sbl", ".SBL", ),
"SQL": (".psql", ".sql", ".SQL", ),
"SQLData": (".data.sql", ),
"SQLStoredProcedure": (".spc.sql", ".spoc.sql", ".sproc.sql", ".udf.sql", ),
"Standard ML": (".fun", ".sig", ".sml", ),
"Swift": (".swift", ),
"Tcl/Tk": (".itk", ".tcl", ".tk", ),
"Teamcentermet": (".met", ),
"Teamcentermth": (".mth", ),
"TitaniumStyleSheet": (".tss", ),
"TypeScript": (".ts", ),
"Unity-Prefab": (".mat", ".prefab", ),
"Vala": (".vala", ),
"ValaHeader": (".vapi", ),
"Velocity Template Language": (".vm", ),
"Verilog-SystemVerilog": (".sv", ".svh", ".v", ),
"VHDL": (".VHD", ".vhd", ".vhdl", ".VHDL", ),
"vimscript": (".vim", ),
"VisualBasic": (".bas", ".cls", ".ctl", ".dsr", ".frm", ".VB", ".vb", ".VBA", ".vba", ".vbs", ".VBS", ),
"VisualFoxPro": (".sca", ".SCA", ),
"VisualforceComponent": (".component", ),
"VisualforcePage": (".page", ),
"WindowsMessageFile": (".mc", ),
"WindowsModuleDefinition": (".def", ),
"WindowsResourceFile": (".rc", ".rc2", ),
"WiXinclude": (".wxi", ),
"WiXsource": (".wxs", ),
"WiXstring": (".wxl", ),
"XAML": (".xaml", ),
"xBase": (".prg", ),
"xBaseHeader": (".ch", ),
"XML": (".XML", ".xml", ),
"XQuery": (".xq", ".xquery", ),
"XSD": (".xsd", ".XSD", ),
"XSLT": (".xsl", ".XSL", ".xslt", ".XSLT", ),
"yacc": (".y", ),
"YAML": (".yaml", ".yml", )}
